apiVersion: batch/v1
kind: Job
metadata:
  # As kubernetes does not allow updating the job spec, the job needs to be recreated upon any
  # secret configuration changes. We force this by appending the sha1sum of the configuration to
  # the name.
  name: {{ include "idempotent-secrets.fullname" $ }}-{{ toString $.Values.secrets | sha1sum }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: idempotent-secrets
          image: {{ include "idempotent-secrets.image" $ }}
          imagePullPolicy: IfNotPresent
          args:
            - "idempotent-secrets"
            - --namespace
            - {{ $.Release.Namespace }}
{{- range $secret := .Values.secrets }}
            - --json
            - {{ $secret | toJson | quote }}
{{- end }}
            - --anchor-name
            - {{ include "idempotent-secrets.fullname" $ }}-anchor
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            # We mount the anchor secret to ensure that it is created before the job runs.
            - name: anchor-secret
              mountPath: /anchor-secret
              readOnly: true
      volumes:
        - name: anchor-secret
          secret:
            secretName: {{ include "idempotent-secrets.fullname" $ }}-anchor
      restartPolicy: Never
      serviceAccountName: {{ include "idempotent-secrets.fullname" $ }}
---
